spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:reccos
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      "[format_sql]": true
  h2:
    console:
      enabled: true
      path: /h2-console