spring:
  datasource:
    username: root
    password: BemAgro
    url: jdbc:mysql://localhost:3306/reccoshop?useTimezone=true&serverTimezone=UTC
  jpa:
    show-sql: true
    properties:
      "[format_sql]": true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect