server:
  port: ${RECCOS_PORT}
spring:
  datasource:
    username: ${RECCOS_DB_USER}
    password: ${RECCOS_DB_PASSWORD}
    url: jdbc:mysql://${RECCOS_DB_HOST}:${RECCOS_DB_PORT}/${RECCOS_DB_NAME}?serverTimezone=UTC
  jpa:
    show-sql: false
    properties:
      "[format_sql]": false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true