spring:
  flyway:
    enabled: true
    repair: true
  web:
    locale: pt_BR
  profiles:
    active: ${HYPERPROF_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: none
jwt:
   secret: ${JWT_SECRET:reccos-secrety-key} 